# pre-commit is a linter runner and GitHub hook manager
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Run `pre-commit autoupdate` now and then, why don't ya?

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [ '--maxkb=2200' ]
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

  # Linter for markdown files
  # This hook uses DavidAnson Node.js markdownlint in a Docker to minimize dev environment at the cost of speed
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        language: docker_image
        entry: ghcr.io/igorshubovych/markdownlint-cli:v0.31.1

  # Scan for secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks-docker
